### PR TITLE
Add currentLocale meta to form & detail

### PR DESCRIPTION
**Pull request by d8vjork**
This should solve #27

### CODE REVIEW

**Comment by mrmonat** [comment]
Thank you, merged :)

**Comment by milewski** [comment]
Just a small note @mrmonat always compile the assets by yourself... it is generally risk to accept minified assets from contributors it can contain malicious script mixed in which are directly delivered to all the users of this package.

**Comment by mrmonat** [comment]
@milewski You are right, but I "compiled" the pull request locally, and it was exactly the same like in this pull request :)

**Comment by royduin** [comment]
Please revert, see: https://github.com/mrmonat/nova-translatable/issues/44

**Pull request merged**
